### ISSUE TITLE
Blip Sprite ... Not an issue!

### ISSUE THREAD

**Issue by FreakyMan82** [XxFri3ndlyxX/esx_kuana_impound#1]
Hi (again)! :)
The blip sprite 477 doesn't work (not showing on the map), others do (tested with 50, 67) ;). So, till the official fix, change the blip sprite id. (https://wiki.gtanet.work/index.php?title=Blips)

**Comment by XxFri3ndlyxX** [comment]
Hi the blip works. But will disappear if you restart the script. So no fix is needed.

**Comment by FreakyMan82** [comment]
i restarted the server with cache deleted... no blip, restart the plugin nothing... changed to other blip id ... restarted the server with cache deleted, always show up ... so don't know ... but for me the 477 blip doesnt work...others do..

**Comment by FreakyMan82** [comment]
is not a problem, easy fixed ... but to let you know that, for me, 477 doesnt show up... ;)

**Comment by FreakyMan82** [comment]
you can delete these "issue" ... i  saw your discord ... maybe for future problems i will contact you there ...

**Comment by XxFri3ndlyxX** [comment]
I literally download the clone. Cleared my cache and then start the server and the blip works. SO for me there is nothing to fix. You might have some sort of conflict somewhere. But if you changed it and works. Then that's all what it matters. I consider this issue as fix then :)  Feel free to reopen a new issue if needed Thanks! And yes discord is a better better place than here

**Comment by goufbam** [comment]
one issue could be you have more then 100 map icons that could be why it doesn't show up maybe.
